# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  paths:
    include:
      - src/Services/Identity/**
      - src/Shared/**

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'f0bba39a-badd-44e3-a3d7-b1142b99c980'
  imageRepository: 'blockticket-identity'
  containerRegistry: 'blockticket.azurecr.io'
  dockerfilePath: 'src/Services/Identity/Identity.API/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  name: 'blockticket'

stages:
- stage: Build
  displayName: Build and Push
  jobs:
  - job: BuildAndPush
    displayName: Build and Push Identity Service
    steps:
    - task: Docker@2
      displayName: Build and push image to container registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/$(dockerfilePath)'
        buildContext: '$(Build.SourcesDirectory)'
        tags: |
          $(tag)
          latest
