apiVersion: v1
kind: Secret
metadata:
  name: identity-secret
$patch: delete
---
apiVersion: v1
kind: Secret
metadata:
  name: event-secret
$patch: delete
---
apiVersion: v1
kind: Secret
metadata:
  name: ticketing-secret
$patch: delete
---
apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
$patch: delete
---
apiVersion: v1
kind: Secret
metadata:
  name: verification-secret
$patch: delete
