apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blockticket-dev
  namespace: argocd
spec:
  project: blockticket
  source:
    repoURL: https://github.com/replace-with-org/Block_Ticket.git
    targetRevision: main
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: blockticket-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blockticket-staging
  namespace: argocd
spec:
  project: blockticket
  source:
    repoURL: https://github.com/replace-with-org/Block_Ticket.git
    targetRevision: main
    path: k8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: blockticket-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blockticket-prod
  namespace: argocd
spec:
  project: blockticket
  source:
    repoURL: https://github.com/replace-with-org/Block_Ticket.git
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: blockticket
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
