apiVersion: v1
kind: Namespace
metadata:
  name: blockticket
  labels:
    name: blockticket
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: blockticket-dev
  labels:
    name: blockticket-dev
    environment: development













