apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-gateway-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: api-gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: identity-service-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: identity-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: event-service-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: event-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ticketing-service-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ticketing-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: notification-service-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: notification-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: resale-service-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: resale-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: verification-service-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: verification-service
