apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../namespace.yaml
  - ../services/api-gateway.yaml
  - ../services/identity-service.yaml
  - ../services/event-service.yaml
  - ../services/ticketing-service.yaml
  - ../services/notification-service.yaml
  - ../services/resale-service.yaml
  - ../services/verification-service.yaml
  - ../policies/network-policies.yaml
  - ../policies/pod-disruption-budgets.yaml
  - ../scaling/hpa.yaml
