apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  ASPNETCORE_ENVIRONMENT: "Staging"
  IdentityServer__Authority: "https://staging.blockticket.example.com"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.monitoring:4317"
  OTEL_SERVICE_NAME: "api-gateway"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-config
data:
  ASPNETCORE_ENVIRONMENT: "Staging"
  Application__BaseUrl: "https://staging.blockticket.example.com"
  Cors__AllowedOrigins__0: "https://staging.blockticket.example.com"
  Email__SmtpHost: "replace-with-smtp-host"
  Email__SmtpPort: "587"
  RabbitMQ__Username: "blockticket"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.monitoring:4317"
  OTEL_SERVICE_NAME: "identity-service"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: event-config
data:
  ASPNETCORE_ENVIRONMENT: "Staging"
  Security__AllowedOrigins__0: "https://staging.blockticket.example.com"
  RabbitMQ__Username: "blockticket"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.monitoring:4317"
  OTEL_SERVICE_NAME: "event-service"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ticketing-config
data:
  ASPNETCORE_ENVIRONMENT: "Staging"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.monitoring:4317"
  OTEL_SERVICE_NAME: "ticketing-service"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
data:
  ASPNETCORE_ENVIRONMENT: "Staging"
  RabbitMQ__Username: "blockticket"
  Email__SmtpHost: "replace-with-smtp-host"
  Email__SmtpPort: "587"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.monitoring:4317"
  OTEL_SERVICE_NAME: "notification-service"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: resale-config
data:
  ASPNETCORE_ENVIRONMENT: "Staging"
  IdentityServer__Authority: "https://staging.blockticket.example.com"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.monitoring:4317"
  OTEL_SERVICE_NAME: "resale-service"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: verification-config
data:
  ASPNETCORE_ENVIRONMENT: "Staging"
  IdentityServer__Authority: "https://staging.blockticket.example.com"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.monitoring:4317"
  OTEL_SERVICE_NAME: "verification-service"
