apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: identity-secret
spec:
  data:
  - secretKey: ConnectionStrings__DefaultConnection
    remoteRef:
      key: blockticket-staging/app
      property: postgres_connection_string
  - secretKey: ConnectionStrings__Redis
    remoteRef:
      key: blockticket-staging/app
      property: redis_connection_string
  - secretKey: Security__JwtSecretKey
    remoteRef:
      key: blockticket-staging/app
      property: identity_jwt_secret
  - secretKey: Security__EncryptionKey
    remoteRef:
      key: blockticket-staging/app
      property: identity_encryption_key
  - secretKey: JWT__SecretKey
    remoteRef:
      key: blockticket-staging/app
      property: identity_jwt_secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: event-secret
spec:
  data:
  - secretKey: ConnectionStrings__DefaultConnection
    remoteRef:
      key: blockticket-staging/app
      property: postgres_connection_string
  - secretKey: ConnectionStrings__Redis
    remoteRef:
      key: blockticket-staging/app
      property: redis_connection_string
  - secretKey: ConnectionStrings__RabbitMQ
    remoteRef:
      key: blockticket-staging/app
      property: rabbitmq_connection_string
  - secretKey: RabbitMQ__Password
    remoteRef:
      key: blockticket-staging/app
      property: rabbitmq_password
  - secretKey: Security__JwtSettings__SecretKey
    remoteRef:
      key: blockticket-staging/app
      property: event_jwt_secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ticketing-secret
spec:
  data:
  - secretKey: ConnectionStrings__DefaultConnection
    remoteRef:
      key: blockticket-staging/app
      property: postgres_connection_string
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: notification-secret
spec:
  data:
  - secretKey: ConnectionStrings__DefaultConnection
    remoteRef:
      key: blockticket-staging/app
      property: postgres_connection_string
  - secretKey: ConnectionStrings__RabbitMQ
    remoteRef:
      key: blockticket-staging/app
      property: rabbitmq_connection_string
  - secretKey: RabbitMQ__Password
    remoteRef:
      key: blockticket-staging/app
      property: rabbitmq_password
  - secretKey: Email__SmtpPassword
    remoteRef:
      key: blockticket-staging/app
      property: notification_smtp_password
  - secretKey: Sms__TwilioAccountSid
    remoteRef:
      key: blockticket-staging/app
      property: notification_twilio_account_sid
  - secretKey: Sms__TwilioAuthToken
    remoteRef:
      key: blockticket-staging/app
      property: notification_twilio_auth_token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: verification-secret
spec:
  data:
  - secretKey: ConnectionStrings__DefaultConnection
    remoteRef:
      key: blockticket-staging/app
      property: postgres_connection_string
